Parameters:
  DesiredCapacity:
    Description: desired capacity of auto scaling group containing web servers
    Type: Number
    Default: 2
  InstanceSubnets:
    Description: List of VPC subnets that instances can be launched in
    Type: CommaDelimitedList

Resources:

  autoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: !Ref DesiredCapacity
      LaunchConfigurationName: !Ref launchConfiguration
      MaxSize: !Ref DesiredCapacity
      MinSize: !Ref DesiredCapacity
      VPCZoneIdentifier: !Ref InstanceSubnets

  launchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceId: !Ref webServer

  webServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []

          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true

    Properties:
      ImageId: ami-7c87d913
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref securityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r webServer --region ${AWS::Region} -v

  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: access web application
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80


Outputs:
  webserverIPAddress:
    Value: !Sub ${webServer.PublicIp}
